### ISSUE TITLE
narrowing from int to char

### ISSUE THREAD

**Issue by susilehtola** [psi4/psi4public#177]
Release 0.3 fails to build with gcc 5.1.1, error is

/builddir/build/BUILD/psi4public-1881450f30d3bd2ac91dbc4fc6a4eaa5c9f03ae5/src/lib/libmints/basisset_parser.cc: In member function 'virtual std::vector<psi::ShellInfo> psi::Gaussian94BasisSetParser::parse(const string&, const std::vector<std::basic_string<char> >&)':
/builddir/build/BUILD/psi4public-1881450f30d3bd2ac91dbc4fc6a4eaa5c9f03ae5/src/lib/libmints/basisset_parser.cc:176:104: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
     char shell_to_am[] = {-1,-1,-1, 2,-1, 3, 4, 5, 6,-1, 7, 8, 9,10,11, 1,12,13, 0,14,15,16,17,18,19,20};
                                                                                                        ^

**Comment by loriab** [comment]
gcc 5 is a problem. Even architectures that get through building libmints fail on linking. Until Boost is ready, I don't think we'll try too hard to support 5: https://github.com/psi4/psi4public/wiki/9_CXX#-what-gcc-fundamental-libraries-are-approved .

**Comment by susilehtola** [comment]
Well, Boost has been built with gcc 5.1.1 in Fedora.

**Comment by loriab** [comment]
Lovely, they've added gcc 5.1 support in boost 1.59 (1.58 didn't: http://www.boost.org/users/history/version_1_58_0.html). Thanks for the information.

**Comment by susilehtola** [comment]
Fedora 22 has boost 1.57 and gcc 5 :)

**Comment by jturney** [comment]
@susilehtola Can you confirm this resolves the issue?

**Comment by susilehtola** [comment]
Yes, that did the trick.
